# ============================================================================
#
# The configuration produced by default is meant to highlight the features
# that Zensical provides and to serve as a starting point for your own
# projects.
#
# ============================================================================

[project]

# The site_name is shown in the page header and the browser window title
#
# Read more: https://zensical.org/docs/setup/basics/#site_name
site_name = "SWIG"

# The site_description is included in the HTML head and should contain a
# meaningful description of the site content for use by search engines.
#
# Read more: https://zensical.org/docs/setup/basics/#site_description
site_description = "SWIG documentation."

# The site_author attribute. This is used in the HTML head element.
#
# Read more: https://zensical.org/docs/setup/basics/#site_author
# site_author = ""

# The site_url is the canonical URL for your site. When building online
# documentation you should set this.
# Read more: https://zensical.org/docs/setup/basics/#site_url
#site_url = "https://www.example.com/"

# The copyright notice appears in the page footer and can contain an HTML
# fragment.
#
# Read more: https://zensical.org/docs/setup/basics/#copyright
# copyright = """
# Copyright &copy; 2026 The authors
# """

# Zensical supports both implicit navigation and explicitly defined navigation.
# If you decide not to define a navigation here then Zensical will simply
# derive the navigation structure from the directory structure of your
# "docs_dir". The definition below demonstrates how a navigation structure
# can be defined using TOML syntax.
#
# Read more: https://zensical.org/docs/setup/navigation/
nav = [
    "index.md",
    { "latest" = [
        "latest/Preface.md", 
        "latest/Introduction.md", 
        "latest/Windows.md", 
        "latest/Scripting.md", 
        "latest/SWIG.md", 
        "latest/SWIGPlus.md", 
        "latest/CPlusPlus11.md", 
        "latest/CPlusPlus14.md", 
        "latest/CPlusPlus17.md", 
        "latest/CPlusPlus20.md", 
        "latest/CPlusPlus23.md", 
        "latest/CPlusPlus26.md", 
        "latest/Preprocessor.md", 
        "latest/Library.md", 
        "latest/Arguments.md", 
        "latest/Typemaps.md", 
        "latest/Customization.md", 
        "latest/Contract.md", 
        "latest/Varargs.md", 
        "latest/Doxygen.md", 
        "latest/Warnings.md", 
        "latest/Modules.md", 
        "latest/CCache.md", 
        "latest/Android.md", 
        "latest/CSharp.md", 
        "latest/D.md", 
        "latest/Go.md", 
        "latest/Guile.md", 
        "latest/Java.md", 
        "latest/Javascript.md", 
        "latest/Lua.md", 
        "latest/Octave.md", 
        "latest/Perl5.md", 
        "latest/Php.md", 
        "latest/Python.md", 
        "latest/R.md", 
        "latest/Ruby.md", 
        "latest/Scilab.md", 
        "latest/Tcl.md", 
        "latest/C.md", 
        "latest/Ocaml.md", 
        "latest/Extending.md", 
    ] },
    { "v4.5.0" = [
        "Doc4.5/Preface.md", 
        "Doc4.5/Introduction.md", 
        "Doc4.5/Windows.md", 
        "Doc4.5/Scripting.md", 
        "Doc4.5/SWIG.md", 
        "Doc4.5/SWIGPlus.md", 
        "Doc4.5/CPlusPlus11.md", 
        "Doc4.5/CPlusPlus14.md", 
        "Doc4.5/CPlusPlus17.md", 
        "Doc4.5/CPlusPlus20.md", 
        "Doc4.5/Preprocessor.md", 
        "Doc4.5/Library.md", 
        "Doc4.5/Arguments.md", 
        "Doc4.5/Typemaps.md", 
        "Doc4.5/Customization.md", 
        "Doc4.5/Contract.md", 
        "Doc4.5/Varargs.md", 
        "Doc4.5/Doxygen.md", 
        "Doc4.5/Warnings.md", 
        "Doc4.5/Modules.md", 
        "Doc4.5/CCache.md", 
        "Doc4.5/Android.md", 
        "Doc4.5/CSharp.md", 
        "Doc4.5/D.md", 
        "Doc4.5/Go.md", 
        "Doc4.5/Guile.md", 
        "Doc4.5/Java.md", 
        "Doc4.5/Javascript.md", 
        "Doc4.5/Lua.md", 
        "Doc4.5/Octave.md", 
        "Doc4.5/Perl5.md", 
        "Doc4.5/Php.md", 
        "Doc4.5/Python.md", 
        "Doc4.5/R.md", 
        "Doc4.5/Ruby.md", 
        "Doc4.5/Scilab.md", 
        "Doc4.5/Tcl.md", 
        "Doc4.5/C.md", 
        "Doc4.5/Ocaml.md", 
        "Doc4.5/Extending.md", 
    ] },
]

# ----------------------------------------------------------------------------
# In the "palette" subsection you can configure options for the color scheme.
# You can configure different color # schemes, e.g., to turn on dark mode,
# that the user can switch between. Each color scheme can be further
# customized.
#
# Read more:
# - https://zensical.org/docs/setup/colors/
# ----------------------------------------------------------------------------
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

# ----------------------------------------------------------------------------
# In the "font" subsection you can configure the fonts used. By default, fonts
# are loaded from Google Fonts, giving you a wide range of choices from a set
# of suitably licensed fonts. There are options for a normal text font and for
# a monospaced font used in code blocks.
# ----------------------------------------------------------------------------
[project.theme.font]
text = "Lato"
code = "Inconsolata SemiExpanded" # "Source Code Pro"

# ----------------------------------------------------------------------------
# You can configure your own logo to be shown in the header using the "logo"
# option in the "icons" subsection. The logo can be a path to a file in your
# "docs_dir" or it can be a path to an icon.
#
# Likewise, you can customize the logo used for the repository section of the
# header. Zensical derives the default logo for this from the repository URL.
# See below...
#
# There are other icons you can customize. See the documentation for details.
#
# Read more:
# - https://zensical.org/docs/setup/logo-and-icons
# - https://zensical.org/docs/authoring/icons-emojis/#search
# ----------------------------------------------------------------------------
#[project.theme.icon]
#logo = "lucide/smile"
#repo = "lucide/smile"

# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings.
# ----------------------------------------------------------------------------
#[[project.extra.social]]
#icon = "fontawesome/brands/github"
#link = "https://github.com/user/repo"
